Remove upgrade of packages from pip install
The new pip (24.3) has problems with older packages. Errors of the form
```
AttributeError: 'InstallRequirement' object has no attribute 'use_pep517'
```
That are unfixable from the user side.